# 1장. 제어문

## 1절. 조건문
### 1. if/else
- Q) 정수를 입력받아 해당 숫자가 짝수인지 홀수인지 판단하고, 
- 만약 입력받은 숫자가 정수가 아닐 경우 “정수를 입력해주세요.”라는 
- 문구를 출력하는 if문을 작성해보자.

In [5]:
def ifelse(x):
    if x % 2 == 0:
        print(x, "는 짝수!")
    elif x % 2 == 1:
        print(x, "는 홀수!")
    else :
        print("정수를 입력해주세요")

In [9]:
ifelse(3)
ifelse(4)
ifelse(5.5)

3 는 홀수!
4 는 짝수!
정수를 입력해주세요


*2. ifelse*

*Q) 정수를 입력받아 짝수이면 “짝수입니다.”, 홀수이면 “홀수입니다.”를 출력하고,* *정수가 아닐 경우 “정수가 아닙니다.”를 출력하는 ifelse문을 작성해보자. (R)*

## 2. 반복문

### 1. for
- Q) 만약 여러분이 아래에 제시된 데이터를 콘솔창에 출력하고 싶다면 
- print 함수 구문을 4번 수행하는 대신, for문을 사용한 간단한 R 코드를 실행하여 
- 원하는 결과를 더욱 편리하게 얻을 수 있다. 
- 이를 확인하기 위해 반복문을 사용하지 않을 때와 반복문을 사용할 때를 비교해보자.


In [10]:
for i in range(2015,2020):
    print('올해는',i)
# 범위설정 range로 하면 맨끝 포함 x

올해는 2015
올해는 2016
올해는 2017
올해는 2018
올해는 2019


In [11]:
#2. 똑같은거 while문으로 해보기

i = 2015
while i < 2020:
    print('올해는',i)
    i += 1

올해는 2015
올해는 2016
올해는 2017
올해는 2018
올해는 2019


In [3]:
##### list comprehension
#1. Q='I love python' 에서 모음을 제거하고 출력하기

Q = 'I love python'
qq = ''.join([i for i in Q if i not in ['a','e','i','o','u']])
print(qq)

I lv pythn


In [6]:
#2. 3차원 행렬 M=[[1,2,3],[4,5,6],[7,8,9]]을 1차원으로 바꾸기

Matrix = [[1,2,3],
     [4,5,6],
     [7,8,9]]

for i in Matrix:
    print(i)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [12]:
M_list = [i for i in Matrix]
print(M_list)

M_list2 = [k for i in Matrix for k in i]
print(M_list2)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


# 2장. 데이터 변환


## 1절 | 파생변수 생성

### 1. $ : data.frame에서의 변수추가

- Q) R의 내장 데이터 iris에 행번호를 담고 있는 ‘ID’ 라는 변수를 새로 생성해보자.


In [13]:
from sklearn.datasets import load_iris
iris = load_iris()

In [16]:
import pandas as pd
iris = pd.DataFrame(data=iris.data, columns=iris.feature_names)

In [17]:
iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [18]:
# iris 데이터의 구조 확인 : 150개의 행과 5개의 변수를 가지고 있다.
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB


In [26]:
# 150개 개체들의 고유번호에 해당하는 'ID' 변수를 새로 생성
iris['ID'] = iris.index+1
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   ID  
0   1  
1   2  
2   3  
3   4  
4   5

### 2. [ ] : 대괄호를 활용한 변수추가

- 생성했던 ID 변수의 값이 짝수이면 A, 
- 홀수이면 B로 분류하는 새로운 변수(변수명 : Group)를 [ ]를 활용하여 생성해보자.


In [42]:
for i in range(len(iris.ID)):
    
    if iris['ID'][i] % 2 == 0:
        iris['Group'][i] = 'A'
    else:
        iris['Group'][i] = 'B'
iris.head()

C:\Users\KEJ\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
C:\Users\KEJ\Anaconda3\lib\site-packages\pandas\core\indexing.py:1637: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_block(indexer, value, name)
C:\Users\KEJ\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   ID Group  
0   1     A  
1   2     B  
2   3     A  
3   4     B  
4   5     A

### 3. transform
- iris 데이터에서 Sepal.Length 변수와 Petal.Length 변수의 값을 더하여 ‘Sum.Length’ 라는 새로운 변수를 생성해보자.

In [44]:
iris['Sum.Length'] = iris['sepal length (cm)'] + iris['petal length (cm)']
iris.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   ID Group  Sum.Length  
0   1     A         6.5  
1   2     B         6.3  
2   3     A         6.0  
3   4     B         6.1  
4   5     A         6.4

### 4. within

- Q) 학생의 id(s1, s2, s3, s4, s5, s6)를 담은 student_id 변수와 시험점수(55, 90, 85, 71, 63, 99)를 담은 score 변수로 구성된 데이터프레임을 생성하자. 
- 그 후 시험점수가 90점 이상이면 수, 80점 이상 90점 미만이면 우, 
- 70점 이상 80점 미만이면 미, 60점 이상 70점 미만이면 양, 
- 60점 이하이면 가로 분류하는 ‘grade’ 라는 변수를 새롭게 생성해보자.

In [57]:
student_id = ['s1','s2','s3','s4','s5','s6']
score = [55,90,85,71,63,99]
df = pd.DataFrame({'student_id':['s1','s2','s3','s4','s5','s6'], 'score' : [55,90,85,71,63,99]} )      
df

student_id  score
0         s1     55
1         s2     90
2         s3     85
3         s4     71
4         s5     63
5         s6     99

In [67]:
grade = [] 
for i in range(6):
    if df['score'][i] >= 90 :
        grade.append('수')
    elif df['score'][i] >= 80 :
        grade.append('우')
    elif df['score'][i] >= 70 :
        grade.append('미')
    elif df['score'][i] >= 60 :
        grade.append('양')
    else :
        grade.append('가')
df['grade'] = grade
df

student_id  score grade
0         s1     55     가
1         s2     90     수
2         s3     85     우
3         s4     71     미
4         s5     63     양
5         s6     99     수

## 2절 | 변수 축소

### 1. 주성분분석

In [68]:
from sklearn.decomposition import PCA
from sklearn import datasets

In [81]:
digits = datasets.load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [99]:
from sklearn.preprocessing import *
features = StandardScaler().fit_transform(digits.data)

pca = PCA(n_components = 0.99, whiten = True)
f_pca = pca.fit_transform(features)
print('원래 특성 개수: ', features.shape[1])
print('줄어든 특성 개수: ', f_pca.shape[1])

원래 특성 개수:  64
줄어든 특성 개수:  54


In [94]:
pca2 = PCA(n_components = 8, whiten = True)
f_pca2 = pca2.fit_transform(features)
print('원래 특성 개수: ', features.shape[1])
print('줄어든 특성 개수: ', f_pca2.shape[1])

원래 특성 개수:  64
줄어든 특성 개수:  8


In [96]:
# 표준화, 정규화

import numpy as np

data=np.random.randint(20 , size=(5,5))
data

array([[ 9,  1,  2,  1, 16],
       [12,  7, 14, 13, 15],
       [ 8,  7,  1, 15, 19],
       [ 3, 15,  2,  8,  2],
       [ 6, 13, 13,  6, 15]])

In [97]:
sklearn_ss = StandardScaler().fit_transform(data) # 표준화
print(sklearn_ss)

[[ 0.46563307 -1.53106363 -0.75637558 -1.51878546  0.44175798]
 [ 1.46341823 -0.32232919  1.30646691  0.87929684  0.27185107]
 [ 0.13303802 -0.32232919 -0.92827912  1.27897723  0.95147873]
 [-1.52993724  1.28931674 -0.75637558 -0.11990412 -1.93693885]
 [-0.53215208  0.88640526  1.13456337 -0.5195845   0.27185107]]


In [100]:
sklearn_ms = MinMaxScaler().fit_transform(data) # 정규화
print(sklearn_ms)

[[0.66666667 0.         0.07692308 0.         0.82352941]
 [1.         0.42857143 1.         0.85714286 0.76470588]
 [0.55555556 0.42857143 0.         1.         1.        ]
 [0.         1.         0.07692308 0.5        0.        ]
 [0.33333333 0.85714286 0.92307692 0.35714286 0.76470588]]
