In [ ]:
x<-c(1,20,20)
x

y<-c("a","b","c")
y

xy<-c(x,y)
xy



In [ ]:
a<-matrix(c(1,2,3,4,5,6),ncol=2)
a
b<-matrix(c(1,2,3,4,5,6,7,8),nrow=2)
b

dimnames(b)<-list(c('r1','r2'),c('c1','c2','c3',"c4"))
b

In [ ]:
c<-matrix(c(1,2,3,4,5,6),ncol=2)
a

t1<-c(10,10)
t2<-c(11,11,11)

rbind(a,t1)

cbind(a,t2)

In [ ]:
a1<-c(100,200,300)
b1<-c("a","b","c")
c1<-c(TRUE,FALSE,FALSE)

data.frame(i=a1,j=b1,k=c1)

In [4]:
array(1:12,dim=c(3,4))

x <- array(1:12,dim = c(3,2,2))
x

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

, , 1

     [,1] [,2]
[1,]    1    4
[2,]    2    5
[3,]    3    6

, , 2

     [,1] [,2]
[1,]    7   10
[2,]    8   11
[3,]    9   12

In [9]:
x = c(1,2,3,4,5)
y = c(10,20,30,40,55)

xy = cbind(x,y)
xy


x y 
[1,] 1 10
[2,] 2 20
[3,] 3 30
[4,] 4 40
[5,] 5 55

In [14]:
xy[-c(2,3)]

[1]  1  4  5 10 20 30 40 55